version: "3.8"
services:
  api:
    image: 093859584130.dkr.ecr.ap-northeast-2.amazonaws.com/docker
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "5000:5000"


